# +––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––+
# |                                                                                                                  |
# |                            Default Configuration for VARO made by Rytrox                                         |
# |                                                                                                                  |
# +––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––+

teams:
  # Decides the max amount of team members in a team
  maxMembers: 2
  # Allow Friendly Fire
  friedly-fire: false
  inventory:
    # Decides how many slots a Team-Inventory should have (number between 0 and 54)
    slots: 6

game:
  # The Start-Date when players are allowed to join
  start: '16:00'
  # The End-Date when all players must leave the server
  end: '22:00'
  # Settings for Playertimes
  playertime:
    # Time in HH:mm how long a game day is
    day-length: '00:15'

    # Players can collect days if they aren't online.
    # This setting
    max-allowed-days: 3

    # Player can skip gamedays.
    # If the player has reached this minimum amount of days he will be banned for the days he skipped
    allowed-skip-days: 2

worldborder:
  # world you play in
  world: 'world'
  # initial size of worldborder
  intialSize: 4000
  # center location
  center:
    x: 0
    y: 80
    z: 0
  suddenDeath:
    # speed of the shrinking (in blocks per second)
    speed: 0.5
    # minimal size that can be reached
    minimal: 20
