# +––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––+
# |                                                                                                                  |
# |                            Default Configuration for VARO made by Rytrox                                         |
# |                                                                                                                  |
# +––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––+

teams:
  # Decides the max amount of team members in a team
  maxMembers: 2
  inventory:
    # Decides how many rows a Team-Inventory should have (number between 1 and 6)
    rows: 1
