name: Varo
version: '${project.version}'
main: de.rytrox.varo.Varo
load: STARTUP
description: Ein Varo-Plugin

commands:
  teams:
    description: 'Manage, erstelle und bearbeite Teams'
    usage: '/teams'
  teaminventory:
    description: 'Öffne dein Teaminventar'
    aliases:
      - teaminv
    usage: '/teaminventory'

permissions:
  varo.*:
    default: op
    description: 'Super-Permission für Varo'
    children:
      - 'varo.teams.*'
  varo.teams.*:
    default: op
    description: 'Super-Permission für das TeamManagement in Varo'
    children:
      - 'varo.teams.add'
      - 'varo.teams.remove'
      - 'varo.teams.modify.*'
      - 'varo.teams.members.*'
  varo.teams.members.*:
    default: op
    description: 'Füge neue Member zu einem Team hinzu und entferne Member von seinem Team'
    children:
      - 'varo.teams.members.add'
      - 'varo.teams.members.remove'
  varo.teams.members.add:
    default: op
    description: 'Füge neue Mitglieder zu einem Team hinzu'
  varo.teams.members.remove:
    default: op
    description: 'Entferne Mitglieder aus einem Team'
  varo.teams.modify.*:
    default: op
    description: 'Bearbeite Teams wie den Displaynamen'
    children:
      - 'varo.teams.modify.displayname'
  varo.teams.modify.displayname:
    description: 'Modifiziere den Displaynamen des Teams'
    default: op
